package uz.abror.websocket;

/**
 * @author Nurislom
 * @since 9/4/2023 2:46 PM
 */
public abstract class PrepareConstants {

    public static final String CREATE_DEPARTMENT = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"PROFILEMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"id\\\":\\\"${msgKey}\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"method\\\":\\\"saveDepartment\\\",\\\"params\\\":{\\\"department\\\":{\\\"id\\\":null,\\\"code\\\":\\\"${code}\\\",\\\"nameUz\\\":\\\"${nameUz}\\\",\\\"nameRu\\\":\\\"${nameRu}\\\",\\\"status\\\":\\\"ACTIVE\\\",\\\"employeeIds\\\":null}}}}\\u0000\"]";
    public static final String CREATE_EMPLOYEE_GAS_STATION = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"PROFILEMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"createDepartmentEmployee\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"requestDTO\\\":{\\\"id\\\":null,\\\"phoneNumber\\\":\\\"${phoneNumber}\\\",\\\"departmentCode\\\":\\\"${departmentCode}\\\",\\\"firstname\\\":\\\"${firstName}\\\",\\\"lastname\\\":\\\"${lastName}\\\",\\\"username\\\":null,\\\"showOdometer\\\":false,\\\"salePoint\\\":\\\"${salePoint}\\\",\\\"status\\\":null,\\\"partnerType\\\":\\\"GAS_STATION\\\"}}}}\\u0000\"]";
    public static final String CREATE_DEPOSIT = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"DEPOSITMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"createSendDepositRequest\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"depositRequestDTO\\\":{\\\"buyerCompanyInn\\\":\\\"${buyerInn}\\\",\\\"buyerCompanyName\\\":null,\\\"sellerCompanyName\\\":\\\"305644040\\\",\\\"signetDocNumber\\\":\\\"911808705044\\\",\\\"sellerCompanyInn\\\":\\\"${sellerInn}\\\",\\\"amount\\\":${amount},\\\"comment\\\":\\\"test\\\",\\\"unit\\\":null,\\\"buyerDepartmentUsername\\\":\\\"${buyerInn}\\\",\\\"createdAt\\\":\\\"2023-09-08T02:04:00.580Z\\\",\\\"status\\\":\\\"ACTIVE\\\"}}}}\\u0000\"]";
    public static final String CHECK_DEPOSIT = "[\"\"]";
    public static final String GET_PAYMENTS = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"PAYMENTMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"getPayment\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"pageable\\\":{\\\"page\\\":0,\\\"size\\\":10,\\\"sort\\\":null,\\\"orderBy\\\":\\\"DESC\\\",\\\"properties\\\":[\\\"id\\\"]},\\\"criteria\\\":{}}}}\\u0000\"]";
    public static final String APPROVE = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"PAYMENTMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"approve\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"1\\\",\\\"params\\\":{\\\"paymentId\\\":${paymentId}}}}}\\u0000\"]";
    public static final String PAY = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"PAYMENTMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"pay\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"payment\\\":{\\\"date\\\":\\\"${date_now}\\\",\\\"sellerMerchantInn\\\":${sellerMerchantInn},\\\"sellerTerminal\\\":\\\"HUMO\\\",\\\"cashier\\\":null,\\\"sellerDepartmentName\\\":\\\"${sellerDepartmentName}\\\",\\\"buyerPan\\\":\\\"${buyerPan}\\\",\\\"buyerMerchantInn\\\":\\\"${buyerMerchantInn}\\\",\\\"buyerEmployeeName\\\":null,\\\"buyerVehicleNumber\\\":\\\"${buyerVehicleNumber}\\\",\\\"productCode\\\":\\\"${productCode}\\\",\\\"unitPrice\\\":\\\"${unitPrice}\\\",\\\"unitAmount\\\":\\\"${unitAmount}\\\",\\\"totalPrice\\\":\\\"${totalPrice}\\\",\\\"productUnit\\\":\\\"${productUnit}\\\",\\\"odometer\\\":null,\\\"cardToken\\\":\\\"${cardToken}\\\"}}}}\\u0000\"]";
    public static final String PAY_HISTORY_BY_USERNAME = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"PAYMENTMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"272272272\\\",\\\"data\\\":{\\\"method\\\":\\\"getPaymentHistoryByUsername\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"requestPaymentDTO\\\":{\\\"username\\\":\\\"${username}\\\",\\\"timeDTO\\\":{\\\"startData\\\":\\\"${startInstant}\\\",\\\"endData\\\":\\\"${endInstant}\\\"}}}}}\\u0000\"]";
    public static final String GET_DEPOSIT_REQUEST_BY_ID = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"DEPOSITMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"getDepositRequestById\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"id\\\":${id}}}}\\u0000\"]";
    public static final String APPROVE_OR_CANCEL_DEPOSIT = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"DEPOSITMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"ApproveOrCancelTheDepositRequest\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"depositRequestDTO\\\":{\\\"id\\\":${depositRequestId},\\\"depositTransactionId\\\":null,\\\"sellerCompanyInn\\\":\\\"${username}\\\",\\\"sellerCompanyName\\\":\\\"DEVOPS\\\",\\\"buyerCompanyInn\\\":\\\"${buyerInn}\\\",\\\"buyerCompanyName\\\":\\\"DEVOPS\\\",\\\"createdAt\\\":\\\"2023-09-08T06:04:54.599015Z\\\",\\\"amount\\\":${amount},\\\"unit\\\":null,\\\"status\\\":\\\"APPROVED\\\",\\\"comment\\\":\\\"test\\\",\\\"productCode\\\":null,\\\"senderUsername\\\":null,\\\"recipientUsername\\\":null}}}}\\u0000\"]";
    public static final String SEND_NOTIFICATION = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"NOTIFICATIONMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"recipientUsername\\\":null,\\\"sendUsername\\\":true,\\\"data\\\":{\\\"method\\\":\\\"sendNotification\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"params\\\":{\\\"notificationDTO\\\":{\\\"id\\\":${id},\\\"senderUsername\\\":\\\"${username}\\\",\\\"recipientUsername\\\":\\\"${recipientUsername}\\\",\\\"createdAt\\\":\\\"2023-09-08T05:35:59.069079Z\\\",\\\"status\\\":\\\"NEW\\\",\\\"depositRequestId\\\":${id}}}}}\\u0000\"]";
    public static final String ATTACH_VEHICLE = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"FUELMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"attachVehicleToEmployee\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"request\\\":{\\\"username\\\":\\\"${emp_username}\\\",\\\"vehicleId\\\":${vehicleId}}}}}\\u0000\"]";
    public static final String CREATE_EMPLOYEE_CARD_LIMIT = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"PAYMENTMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"saveCardLimit\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"cardLimit\\\":{\\\"periodic\\\":\\\"DAY\\\",\\\"resetValue\\\":${resetValue},\\\"startedDate\\\":\\\"2023-09-08T12:07:11.296Z\\\",\\\"username\\\":\\\"${emp_username}\\\"}}}}\\u0000\"]";
    public static final String CREATE_VEHICLE = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"FUELMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"373373373\\\",\\\"data\\\":{\\\"method\\\":\\\"createVehicle\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"1\\\",\\\"params\\\":{\\\"vehicle\\\":{\\\"id\\\":null,\\\"model\\\":{\\\"id\\\":2,\\\"name\\\":\\\"Aveo\\\",\\\"status\\\":\\\"ACTIVE\\\",\\\"brandName\\\":null,\\\"brand\\\":{\\\"id\\\":1,\\\"name\\\":\\\"Chevrolet\\\",\\\"status\\\":\\\"ACTIVE\\\"}},\\\"status\\\":\\\"NEW\\\",\\\"govNumber\\\":\\\"01A999AA\\\",\\\"color\\\":\\\"#0e1929\\\",\\\"odometer\\\":340}}}}\\u0000\"]";
    public static final String CREATE_EMPLOYEE_BUSINESS = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"PROFILEMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"createDepartmentEmployee\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"requestDTO\\\":{\\\"id\\\":null,\\\"phoneNumber\\\":\\\"${phoneNumber}\\\",\\\"departmentCode\\\":\\\"${departmentCode}\\\",\\\"firstname\\\":\\\"${firstName}\\\",\\\"lastname\\\":\\\"${lastName}\\\",\\\"username\\\":null,\\\"showOdometer\\\":false,\\\"salePoint\\\":null,\\\"status\\\":null,\\\"partnerType\\\":\\\"BUSINESS\\\"}}}}\\u0000\"]";
    public static final String CREATE_SALE_POINT = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"PRODUCTMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"createSalePoint\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"SalePoint\\\":{\\\"id\\\":null,\\\"code\\\":null,\\\"nameUz\\\":\\\"${nameUz}\\\",\\\"nameRu\\\":\\\"${nameRu}\\\",\\\"addressUz\\\":\\\"${addressUz}\\\",\\\"addressRu\\\":\\\"${addressRu}\\\",\\\"latitude\\\":41.3298130795676,\\\"longitude\\\":69.24094605660501,\\\"departmentId\\\":${departmentId},\\\"departmentName\\\":\\\"${departmentName}\\\",\\\"merchantInn\\\":\\\"${username}\\\",\\\"status\\\":\\\"ACTIVE\\\"}}}}\\u0000\"]";
    public static final String UPDATE_SALE_POINT = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"PRODUCTMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"updateSalePoint\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"salePoint\\\":{\\\"id\\\":${id},\\\"code\\\":\\\"${code}\\\",\\\"nameUz\\\":\\\"${nameUz}\\\",\\\"nameRu\\\":\\\"${nameRu}\\\",\\\"addressUz\\\":\\\"${addressUz}\\\",\\\"addressRu\\\":\\\"${addressRu}\\\",\\\"latitude\\\":41.3298130795676,\\\"longitude\\\":69.24094605660501,\\\"departmentId\\\":${departmentId},\\\"departmentName\\\":\\\"${departmentName}\\\",\\\"merchantInn\\\":\\\"${username}\\\",\\\"status\\\":\\\"ACTIVE\\\"}}}}\\u0000\"]";
    public static final String CREATE_OFFER = "[\"SEND\\ndestination:/app/topic/handler\\n\\n\\n{\\\"service\\\":\\\"PRODUCTMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"createProductOffer\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"ProductOffer\\\":{\\\"id\\\":null,\\\"price\\\":${price},\\\"departmentId\\\":${departmentId},\\\"departmentName\\\":\\\"${departmentName}\\\",\\\"salePoint\\\":{\\\"id\\\":${idSalePoint},\\\"code\\\":\\\"${codeSalePoint}\\\",\\\"nameUz\\\":\\\"${nameUzSalePoint}\\\",\\\"nameRu\\\":\\\"${nameRuSalePoint}\\\",\\\"addressUz\\\":\\\"${addressUz}\\\",\\\"addressRu\\\":\\\"${addressRu}\\\",\\\"longitude\\\":${longitude},\\\"latitude\\\":${latitude},\\\"status\\\":\\\"ACTIVE\\\",\\\"merchantInn\\\":\\\"${username}\\\",\\\"departmentId\\\":\\\"${departmentIdSalePoint}\\\",\\\"departmentName\\\":\\\"${departmentNameSalePoint}\\\",\\\"contract\\\":null},\\\"product\\\":{\\\"id\\\":${idProduct},\\\"code\\\":\\\"${codeProduct}\\\",\\\"nameUz\\\":\\\"${nameUzProduct}\\\",\\\"nameRu\\\":\\\"${nameRuProduct}\\\",\\\"status\\\":\\\"NEW\\\",\\\"spic\\\":\\\"${spic}\\\",\\\"merchantInn\\\":\\\"${username}\\\",\\\"unitName\\\":\\\"${unitName}\\\",\\\"categoryName\\\":\\\"${categoryName}\\\",\\\"unit\\\":{\\\"id\\\":${idUnit},\\\"code\\\":\\\"${codeUnit}\\\",\\\"nameUz\\\":\\\"${nameUzUnit}\\\",\\\"nameRu\\\":\\\"${nameRuUnit}\\\",\\\"merchantInn\\\":null},\\\"category\\\":{\\\"id\\\":${idCategory},\\\"code\\\":\\\"${codeCategory}\\\",\\\"nameUz\\\":\\\"${nameUzCategory}\\\",\\\"nameRu\\\":\\\"${nameRuCategory}\\\",\\\"status\\\":\\\"NEW\\\",\\\"merchantInn\\\":null}},\\\"status\\\":\\\"ACTIVE\\\"}}}}\\u0000\"]";
    public static final String UPDATE_OFFER = "[\"SEND\\ndestination:/app/topic/handler\\n\\n\\n{\\\"service\\\":\\\"PRODUCTMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"updateProductOffer\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"productOffer\\\":{\\\"id\\\":${id},\\\"price\\\":${price},\\\"departmentId\\\":${departmentId},\\\"departmentName\\\":\\\"${departmentName}\\\",\\\"salePoint\\\":{\\\"id\\\":${idSalePoint},\\\"code\\\":\\\"${codeSalePoint}\\\",\\\"nameUz\\\":\\\"${nameUzSalePoint}\\\",\\\"nameRu\\\":\\\"${nameRuSalePoint}\\\",\\\"addressUz\\\":\\\"${addressUz}\\\",\\\"addressRu\\\":\\\"${addressRu}\\\",\\\"longitude\\\":${longitude},\\\"latitude\\\":${latitude},\\\"status\\\":\\\"ACTIVE\\\",\\\"merchantInn\\\":\\\"${username}\\\",\\\"departmentId\\\":\\\"${departmentIdSalePoint}\\\",\\\"departmentName\\\":\\\"${departmentNameSalePoint}\\\",\\\"contract\\\":null},\\\"product\\\":{\\\"id\\\":${idProduct},\\\"code\\\":\\\"${codeProduct}\\\",\\\"nameUz\\\":\\\"${nameUzProduct}\\\",\\\"nameRu\\\":\\\"${nameRuProduct}\\\",\\\"status\\\":\\\"NEW\\\",\\\"spic\\\":\\\"${spic}\\\",\\\"merchantInn\\\":\\\"${username}\\\",\\\"unitName\\\":\\\"${unitName}\\\",\\\"categoryName\\\":\\\"${categoryName}\\\",\\\"unit\\\":{\\\"id\\\":${idUnit},\\\"code\\\":\\\"${codeUnit}\\\",\\\"nameUz\\\":\\\"${nameUzUnit}\\\",\\\"nameRu\\\":\\\"${nameRuUnit}\\\",\\\"merchantInn\\\":null},\\\"category\\\":{\\\"id\\\":${idCategory},\\\"code\\\":\\\"${codeCategory}\\\",\\\"nameUz\\\":\\\"${nameUzCategory}\\\",\\\"nameRu\\\":\\\"${nameRuCategory}\\\",\\\"status\\\":\\\"NEW\\\",\\\"merchantInn\\\":null}},\\\"status\\\":\\\"ACTIVE\\\"}}}}\\u0000\"]";
    public static final String CREATE_PRODUCT = "[\"SEND\\ndestination:/app/topic/handler\\n\\n{\\\"service\\\":\\\"PRODUCTMS\\\",\\\"destination\\\":\\\"/app/topic/handler\\\",\\\"username\\\":\\\"${username}\\\",\\\"data\\\":{\\\"method\\\":\\\"createProduct\\\",\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":\\\"${msgKey}\\\",\\\"params\\\":{\\\"productDTO\\\":{\\\"id\\\":null,\\\"code\\\":null,\\\"nameUz\\\":\\\"${nameUz}\\\",\\\"nameRu\\\":\\\"${nameRu}\\\",\\\"spic\\\":\\\"${spic}\\\",\\\"unit\\\":{\\\"id\\\":21,\\\"code\\\":\\\"1691366648983\\\",\\\"nameUz\\\":\\\"m3\\\",\\\"nameRu\\\":\\\"m3\\\",\\\"merchantInn\\\":\\\"222222222\\\"},\\\"category\\\":{\\\"id\\\":20,\\\"code\\\":\\\"1693394103332\\\",\\\"nameUz\\\":\\\"43242\\\",\\\"nameRu\\\":\\\"545435\\\",\\\"status\\\":\\\"NEW\\\",\\\"merchantInn\\\":\\\"222222222\\\"},\\\"status\\\":\\\"ACTIVE\\\"}}}}\\u0000\"]";
    public static final String SUB_0 = "[\"SUBSCRIBE\\nid:sub-0\\ndestination:/app/topic/send\\n\\n\\u0000\"]";
    public static final String SUB_1 = "[\"SUBSCRIBE\\nid:sub-1\\ndestination:/user/topic/rpc\\n\\n\\u0000\"]";

    public static final String BUSINESS_KEY = "business";
    public static final String GAS_STATION_KEY = "gas_station";
    public static final String EMPLOYEE_PASSWORD = "12345678";

    public static String connectWss(String token) {
        return "[\"CONNECT\\nAuthorization:Bearer " + token +
                "\\naccept-version:1.1,1.0\\nheart-beat:10000,10000\\n\\n\\u0000\"]";
    }

}
